# --- Serving options --- #
# If you are building a GitHub project page then use these settings:
# url is the full website URL
url: "https://chrischizinski.github.io/SNR_R_Group/"
# baseurl is the website's URL without the hostname
baseurl: "/SNR_R_Group"

# Name of website
title: SNR_R_Group

# Short description of your site
description: Repository for SNR's R User Group

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
#avatar: "/img/fishRlogo.JPG"

# List of links in the navigation bar
navbar-links:
  Home: "index"
  Schedule: "schedule"
  Lessons: "blog"
  Contact: "contact"


# --- Footer options --- #
author:
  name: Christopher J. Chizinski
  email: "chrischizinski@gmail.com"
  github: chrischizinski
  twitter: chrischizinski

# Select which links to show in the footer
footer-links-active:
  email: true
  github: true
  twitter: true
  facebook: false
  rss: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
url-pretty: "chrischizinski.github.io/SNR_R_Group/"

# --- Pagination options --- #
paginate: 5
paginate_path: "/blog/page:num/"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: snr-r-group

# Fill in your Google Analytics ID to track your website using GA
google_analytics: UA-48496439-2

# --- Don't need to touch anything below here (but you can if you want) --- #
# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: Rouge
permalink: /:year-:month-:day-:title

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# prose.io options
prose:
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - /_includes
    - /_layouts
    - /css
    - /img
    - /js
